setup lint
alpknx/twitter pull request #2
Opened 2022-04-25 18:03 UTC by alpknx

2022-04-25 20:34 UTC, klikkn requested changes

2022-04-25 20:34 UTC, klikkn commented on .eslintrc.json
> + }
add an empty row pls here and below

2022-04-25 20:34 UTC, klikkn commented on .prettierrc
> +	"tslintIntegration": true,
you do not need tslint, it was deprecated

2022-04-25 20:34 UTC, klikkn commented on package.json
> +	 "lint": "eslint \"**/*.{ts,tsx,js,jsx}\"",
format this row

2022-04-26 10:43 UTC, klikkn approved these changes

2022-04-30 18:34 UTC, alpknx commented on src/api/api.ts
> +	config.headers.Authorization = `Bearer ${localStorage.getItem('token')}`
why config.headers as undefinded object?

2022-04-30 18:37 UTC, alpknx commented on src/pages/Login/Login.tsx
> +
need an advice about how to mix usesState and element

2022-07-11 21:56 UTC, closed without merging